config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#landing_page"
  resources :users do
    resources :bookings
  end

  resources :bookings do
    resources :reviews, only: [:destroy, :create, :new]
  end



  get "/humans" => "pages#home"

  # get "users/:id", to: "booking/id/users/id"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Define customer route for requests
  get "/users/:user_id/bookings/:id/accept", to: "bookings#accepted", as: :accepted
  get "/users/:user_id/bookings/:id/reject", to: "bookings#rejected", as: :rejected

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user_bookee, class_name: "User"
  belongs_to :user_booker, class_name: "User"

  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings_as_bookee, class_name: "Booking", foreign_key: :user_bookee_id
  has_many :bookings_as_booker, class_name: "Booker", foreign_key: :user_booker_id

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_first_name_and_task,
                  against: %i[first_name task],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :task, :hourly_price, :location, :description, :role, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :task, :hourly_price, :location, :description, :role, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @today = Date.today
    @user = User.find(params[:user_id])
    @bookings_requested = Booking.where(user_bookee_id: current_user).where(is_accepted: nil).order(:start_date)
    @bookings_as_bookee_active = Booking.where(user_bookee_id: current_user).where("end_date >= ?",
                                                                                   @today).where(is_accepted: true).order(:start_date)
    @bookings_as_bookee_completed = Booking.where(user_bookee_id: current_user).where("end_date < ?",
                                                                                      @today).where(is_accepted: true).order(:start_date)
    @bookings_as_bookee_rejected = Booking.where(user_booker_id: current_user).where("end_date < ?",
                                                                                     @today).where(is_accepted: false).order(:start_date)
    @bookings_pending = Booking.where(user_booker_id: current_user).where("end_date >= ?",
                                                                          @today).where(is_accepted: nil).order(:start_date)
    @bookings_active = Booking.where(user_booker_id: current_user).where("end_date >= ?",
                                                                         @today).where(is_accepted: true).order(:start_date)
    @bookings_completed = Booking.where(user_booker_id: current_user).where("end_date < ?",
                                                                            @today).where(is_accepted: true).order(:start_date)
    @bookings_rejected = Booking.where(user_booker_id: current_user).where("end_date < ?",
                                                                           @today).where(is_accepted: false).order(:start_date)
  end

  def new
    @user = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.user_booker_id = current_user.id
    @booking.user_bookee_id = User.find(params[:user_id]).id
    if @booking.save
      redirect_to user_bookings_path(current_user), notice: "Booking successful!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new(booking: @booking)
  end

  def edit
    @booking = Booking.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to user_booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_booking_path, status: :see_other
  end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.is_accepted = true
    @booking.save
    redirect_to user_bookings_path(current_user), status: :see_other
  end

  def rejected
    @booking = Booking.find(params[:id])
    @booking.is_accepted = false
    @booking.save
    redirect_to user_bookings_path(current_user), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :user_bookee_id, :user_booker_id,
                                    :hours_per_day, :description, :is_accepted)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[landing_page home]

  def home
    @users = User.all
    if params[:query].present?
      sql_query = <<~SQL
        users.first_name ILIKE :query
        OR users.task ILIKE :query
        OR users.last_name ILIKE :query
        OR users.location ILIKE :query
      SQL
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @users = User.all
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to user_path(@booking)
    else
      render "booking/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to booking_path(@review.booking)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @booking = Booking.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_bookee.html.erb
<div class="row mt-5 mb-4 bg-light card">
    <h1 class="pt-4">These people want to book you</h1>
    <div class="mt-2">
      <h4>Pending bookings</h4>
    </div>
    <% if @bookings_requested.empty? %>
      <div>
        <p>You have no pending requests, Human 😔</p>
      </div>
    <% else %>
    <div class="row mx-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Their name</th>
            <th scope="col">User contact</th>
            <th scope="col">Description</th>
            <th scope="col">You could earn</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col">Accept</th>
            <th scope="col">Reject</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings_requested.each do |booking| %>
            <tr>
              <% if booking.user_booker.photo.key.present? == true %>
                <td><%= cl_image_tag booking.user_booker.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
              <% else %>
                <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
              <% end %>
              <td><%= booking.user_booker.first_name%></td>
              <td><%= booking.user_booker.email%></td>
              <td><%= booking.description.capitalize %></td>
              <td>£<%= booking.total_price.round %></td>
              <td></td>
              <td></td>
              <td class="table-accept">
                  <%= link_to "Accept", accepted_path(@user, booking), data: {controller: "confetti", action: "click->confetti#spray"}%></td>
              <td class="table-reject"><%= link_to "Reject", rejected_path(@user, booking) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    <% end %>

    <div class="mt-2">
      <h4>Active bookings</h4>
    </div>
    <% if @bookings_as_bookee_active.empty? %>
      <div>
        <p>You have no active bookings</p>
      </div>
    <% else %>
     <div class="row mx-2">
      <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">User</th>
              <th scope="col">Their name</th>
              <th scope="col">User contact</th>
              <th scope="col">Description</th>
              <th scope="col">You will earn</th>
              <th scope="col"></th>
              <th scope="col"></th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            <% @bookings_as_bookee_active.each do |booking| %>
              <tr>
                <% if booking.user_booker.photo.key.present? == true %>
                  <td><%= cl_image_tag booking.user_booker.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
                <% else %>
                  <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
                <% end %>
                <td><%= booking.user_booker.first_name%></td>
                <td><%= booking.user_booker.email%></td>
                <td><%= booking.description.capitalize %></td>
                <td>£<%= booking.total_price.round %></td>
                <td></td>
                <td></td>
                <td class="table-edit"><%= link_to "Edit", edit_user_booking_path(@user, booking) %></td>
                <td class="table-delete"><%= link_to "Delete", user_booking_path(@user, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you delete this booking?"}%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

    <div class="mt-2">
      <h4>Completed bookings</h4>
    </div>
    <% if @bookings_as_bookee_completed.empty? %>
      <div>
        <p>You have no completed bookings</p>
      </div>
    <% else %>
      <div class="row mx-2">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">User</th>
              <th scope="col">Their name</th>
              <th scope="col">User contact</th>
              <th scope="col">Description</th>
              <th scope="col">You earned</th>
            </tr>
          </thead>
          <tbody>
            <% @bookings_as_bookee_active.each do |booking| %>
              <tr>
                <% if booking.user_booker.photo.key.present? == true %>
                  <td><%= cl_image_tag booking.user_booker.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
                <% else %>
                  <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
                <% end %>
                <td><%= booking.user_booker.first_name%></td>
                <td><%= booking.user_booker.email%></td>
                <td><%= booking.description.capitalize %></td>
                <td>£<%= booking.total_price.round %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
    <div class="mt-2">
      <h4>Rejected bookings</h4>
    </div>
    <% if @bookings_as_bookee_rejected.empty? %>
      <div>
        <p>You have no rejected bookings</p>
      </div>
    <% else %>
      <div class="row mx-2">
        <table class="table table-striped mx-4">
          <thead>
            <tr>
              <th scope="col">User</th>
              <th scope="col">Their name</th>
              <th scope="col">User contact</th>
              <th scope="col">Description</th>
              <th scope="col">You would have earned</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            <% @bookings_as_bookee_active.each do |booking| %>
              <tr>
                <% if booking.user_booker.photo.key.present? == true %>
                  <td><%= cl_image_tag booking.user_booker.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
                <% else %>
                  <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
                <% end %>
                <td><%= booking.user_booker.first_name%></td>
                <td><%= booking.user_booker.email%></td>
                <td><%= booking.description.capitalize %></td>
                <td><%= booking.total_price.round %></td>
                <td class="table-delete"><%= link_to "Delete", user_booking_path(@user, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you delete this booking?"}%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
    </div>

app/views/bookings/_booker.html.erb
<div class="row mt-5 mb-4 bg-white card">
  <h1 class="mt-2">These are Humans you've booked</h1>
  <div class="mt-2">
    <h4>Pending bookings</h4>
  </div>
  <% if @bookings_pending.empty? %>
    <div>
      <p>You have no pending bookings</p>
    </div>
  <% else %>
    <div class="row mx-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Their name</th>
            <th scope="col">User contact</th>
            <th scope="col">Description</th>
            <th scope="col">You will pay</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings_pending.each do |booking| %>
            <tr>
              <% if booking.user_bookee.photo.key.present? == true %>
                <td><%= cl_image_tag booking.user_bookee.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
              <% else %>
                <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
              <% end %>
              <td><%= booking.user_bookee.first_name%></td>
              <td><%= booking.user_bookee.email%></td>
              <td><%= booking.description.capitalize %></td>
              <td>£ <%= booking.total_price.round %></td>
              <% if @bookings_active.empty? == false %>
                <td><%= link_to "Edit", edit_user_booking_path(@user, booking) %></td>
              <% else %>
                <td><%= link_to "View", user_booking_path(@user, booking) %></td>
              <% end %>
              <td class="table-delete"><%= link_to "Delete", user_booking_path(@user, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you delete this booking?"}%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <div class="mt-2">
    <h4>Active bookings</h4>
  </div>
  <% if @bookings_active.empty? %>
    <div>
      <p>You have no active bookings</p>
    </div>
  <% else %>
    <div class="row mx-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Their name</th>
            <th scope="col">User contact</th>
            <th scope="col">Description</th>
            <th scope="col">You pay</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings_active.each do |booking| %>
            <tr>
              <% if booking.user_bookee.photo.key.present? == true %>
                <td><%= cl_image_tag booking.user_bookee.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
              <% else %>
                <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
              <% end %>
              <td><%= booking.user_bookee.first_name%></td>
              <td><%= booking.user_bookee.email%></td>
              <td><%= booking.description.capitalize %></td>
              <td>£ <%= booking.total_price.round %></td>
              <% if @bookings_active.empty? == true %>
                <td><%= link_to "Edit", edit_user_booking_path(@user, booking) %></td>
              <% else %>
                <td><%= link_to "View", user_booking_path(@user, booking) %></td>
              <% end %>
              <td class="table-delete"><%= link_to "Delete", user_booking_path(@user, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you delete this booking?"}%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <h4>Completed bookings</h4>
  <% if @bookings_completed.empty? %>
    <p>You have no completed bookings</p>
  <% else %>
    <div class="row mx-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Their name</th>
            <th scope="col">User contact</th>
            <th scope="col">Description</th>
            <th scope="col">You paid</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings_completed.each do |booking| %>
            <tr>
              <% if booking.user_bookee.photo.key.present? == true %>
                <td><%= cl_image_tag booking.user_bookee.photo.key, height: 25, width: 25, :class => "rounded-circle" %></td>
              <% else %>
                <td><%= image_tag "https://bootdey.com/img/Content/avatar/avatar7.png", height: 25, width: 25, :class => "rounded-circle" %></td>
              <% end %>
              <td><%= booking.user_bookee.first_name%></td>
              <td><%= booking.user_bookee.email%></td>
              <td><%= booking.description.capitalize %></td>
              <td>£ <%= booking.total_price.round %></td>
              <% if @bookings_active.empty? == true %>
                <td><%= link_to "Edit", edit_user_booking_path(@user, booking) %></td>
              <% else %>
                <td><%= link_to "View", user_booking_path(@user, booking) %></td>
              <% end %>
              <td class="table-delete"><%= link_to "Delete", user_booking_path(@user, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you delete this booking?"}%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
  
<div class="container my-4">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 mt-6 mb-6">
      <h1>Edit a booking</h1>
      <%= simple_form_for [@user, @booking] do |f| %>
        <%= f.input :user_bookee_id, disabled: true %>
        <%= f.input :user_booker_id, disabled: true %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.input :hours_per_day %>
        <%= f.input :description %>
        <%= f.input :total_price, disabled: true %>
        <%= f.input :is_accepted, disabled: true %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <% if @user.role == true %>
    <%= render "bookee" %>
    <%= render "booker" %>
  <% else %>
    <%= render "booker" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row mt-4 justify-content-center mt-5">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a booking</h1>
      <%= simple_form_for [@user, @booking] do |f| %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.input :hours_per_day %>
        <%= f.input :description %>
        <%= f.input :total_price %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="mt-4">
    <h1>Your Booking with <%= @booking.user_bookee.first_name %></h1>
  </div>
  <div class="card mt-4 mb-4">
    <div class="card-body">
      <div class="flex">
        <div class="mb-3">
          <% if @booking.user_bookee.photo.key.present? == true %>
            <td><%= cl_image_tag @booking.user_bookee.photo.key, height: 60, width: 60, :class => "rounded-circle" %></td>
          <% else %>
            <td><%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", height: 60, width: 60, :class => "rounded-circle" %></td>
          <% end %>
        </div>
        <h5 class="card-title"><%= @booking.user_bookee.first_name %></h5>
      </div>
      <div class=" row">
        <div class="col-sm">
          <p><strong>Description: </strong><%= @booking.description %></p>
          <p><strong>Start date: </strong><%= @booking.start_date %></p>
          <p><strong>End date: </strong><%= @booking.end_date %></p>
          <%= link_to "Check out this human", user_path(@booking), class: "btn btn-outline-primary", style: "btn-sm" %>
        </div>
        <div class="col-sm">
          <p><strong>Total price: </strong><%= @booking.total_price %></p>
          <p><strong>User Bookee id: </strong><%= @booking.user_bookee_id %></p>
          <p><strong>Booking created at: </strong><%= @booking.created_at %></p>
          <p><strong>Booking updated at: </strong><%= @booking.updated_at %></p>
          <p><strong>Hours per day: </strong><%= @booking.hours_per_day %></p>
          <p><strong>Accepted?: </strong><span class="badge badge-pill badge-info"><%= @booking.is_accepted %></span></p>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h3>Leave a review</h3>
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :comment, placeholder: "Enter a comment about the booking" %>
        <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<div class="mb-4"></div>
<div class="container">
  <div class="card">
    <div class="card-body">
      <div class="col-12 col-sm-12">
        <h3>All Reviews</h3>
        <% @booking.reviews.each do |review| %>
          <div class ="d-inline-flex align-middle">
            <strong>
              <p class="mb-0"><%= review.rating %></p>
            </strong>
            <% review.rating.times do %>
              <i class="fa fa-star fa-stars"></i>
            <% end %>
          </div>
          <p class="mb-0"><%= review.comment %></p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hourlyhumans</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <div class="content">
      <%= yield %>
      <div class="mb-4"></div>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="row mt-4">
      <div class="title-top">
        <h1>Hourly Humans</h1>
        <p>Many humans, little hours</p>
      </div>
    </div>
    <div class="search-bar">
      <%= form_with url: humans_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a human"%>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="grid-card">
      <% @users.reverse.each do |user| %>
        <% if user.role == true %>
          <%= link_to user_path(user) do %>
            <div class="card d-flex">
                <div class="align-items-start flex-column" style="height: 200px;">
                  <div class="p-2">
                    <% if user.photo.key.present? == true %>
                      <%= cl_image_tag user.photo.key, height: 80, width: 80, :class => "rounded-circle" %>
                    <% else %>
                      <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="80">
                    <% end %>
                  </div>
                  <div class="d-flex justify-content-between text">
                    <div class="d-flex flex-column text p-2">
                      <h4><%= user.first_name %></h4>
                      <div class="mini-text">👩‍💻<%= user.task %></div>
                      <div class="mini-text">📍<%= user.location %></div>
                    </div>
                    <div class="d-flex flex-column align-items-top">
                      <div class="price p-1">£<%= user.hourly_price == nil ? user.hourly_price : user.hourly_price.round %></div>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/pages/landing_page.html.erb
<header>
  <!-- This div is  intentionally blank. It creates the transparent black overlay over the video which you can modify in the CSS -->
  <div class="overlay"></div>
  <!-- The HTML5 video element that will create the background video on the header -->
  <video id="background-video" autoplay loop muted poster="https://assets.codepen.io/6093409/river.jpg">
    <source src="https://res.cloudinary.com/dl0lttme2/video/upload/v1677673878/hourlyhumans_jvpzyb.mp4" type="video/mp4">
  </video>
  <!-- The header content -->
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-1"><strong><em>Hourly Humans</em></strong></h1>
        <p class="lead lg-1">Rent humans, for any purpose.</p>
        <a href="/humans" type="button" id="landing-btn" class="btn btn-primary btn-lg">Get started</a>
        <a href="/humans" type="button" id="landing-btn-2" class="btn btn-primary btn-lg">Learn more</a>
      </div>
    </div>
  </div>
</header>

app/views/shared/_nav.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path('logo.png') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Humans", humans_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", user_bookings_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.photo.key.present? == true %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>